//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace toptours1.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TopToursWSSoap", Namespace="http://tempuri.org/")]
    public partial class TopToursWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddReviewWSOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReviewWSOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllReviewsOfRouteWSOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateValueWSOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteReviewWSOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TopToursWS() {
            this.Url = global::toptours1.Properties.Settings.Default.toptours1_localhost_TopToursWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddReviewWSCompletedEventHandler AddReviewWSCompleted;
        
        /// <remarks/>
        public event GetReviewWSCompletedEventHandler GetReviewWSCompleted;
        
        /// <remarks/>
        public event GetAllReviewsOfRouteWSCompletedEventHandler GetAllReviewsOfRouteWSCompleted;
        
        /// <remarks/>
        public event UpdateValueWSCompletedEventHandler UpdateValueWSCompleted;
        
        /// <remarks/>
        public event DeleteReviewWSCompletedEventHandler DeleteReviewWSCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddReviewWS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddReviewWS(string content, int rating, string caption, int customer_id, int route_id) {
            object[] results = this.Invoke("AddReviewWS", new object[] {
                        content,
                        rating,
                        caption,
                        customer_id,
                        route_id});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddReviewWSAsync(string content, int rating, string caption, int customer_id, int route_id) {
            this.AddReviewWSAsync(content, rating, caption, customer_id, route_id, null);
        }
        
        /// <remarks/>
        public void AddReviewWSAsync(string content, int rating, string caption, int customer_id, int route_id, object userState) {
            if ((this.AddReviewWSOperationCompleted == null)) {
                this.AddReviewWSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddReviewWSOperationCompleted);
            }
            this.InvokeAsync("AddReviewWS", new object[] {
                        content,
                        rating,
                        caption,
                        customer_id,
                        route_id}, this.AddReviewWSOperationCompleted, userState);
        }
        
        private void OnAddReviewWSOperationCompleted(object arg) {
            if ((this.AddReviewWSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddReviewWSCompleted(this, new AddReviewWSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetReviewWS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Review GetReviewWS(int customer_id, string caption) {
            object[] results = this.Invoke("GetReviewWS", new object[] {
                        customer_id,
                        caption});
            return ((Review)(results[0]));
        }
        
        /// <remarks/>
        public void GetReviewWSAsync(int customer_id, string caption) {
            this.GetReviewWSAsync(customer_id, caption, null);
        }
        
        /// <remarks/>
        public void GetReviewWSAsync(int customer_id, string caption, object userState) {
            if ((this.GetReviewWSOperationCompleted == null)) {
                this.GetReviewWSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReviewWSOperationCompleted);
            }
            this.InvokeAsync("GetReviewWS", new object[] {
                        customer_id,
                        caption}, this.GetReviewWSOperationCompleted, userState);
        }
        
        private void OnGetReviewWSOperationCompleted(object arg) {
            if ((this.GetReviewWSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReviewWSCompleted(this, new GetReviewWSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllReviewsOfRouteWS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Review[] GetAllReviewsOfRouteWS(int route_id) {
            object[] results = this.Invoke("GetAllReviewsOfRouteWS", new object[] {
                        route_id});
            return ((Review[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllReviewsOfRouteWSAsync(int route_id) {
            this.GetAllReviewsOfRouteWSAsync(route_id, null);
        }
        
        /// <remarks/>
        public void GetAllReviewsOfRouteWSAsync(int route_id, object userState) {
            if ((this.GetAllReviewsOfRouteWSOperationCompleted == null)) {
                this.GetAllReviewsOfRouteWSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllReviewsOfRouteWSOperationCompleted);
            }
            this.InvokeAsync("GetAllReviewsOfRouteWS", new object[] {
                        route_id}, this.GetAllReviewsOfRouteWSOperationCompleted, userState);
        }
        
        private void OnGetAllReviewsOfRouteWSOperationCompleted(object arg) {
            if ((this.GetAllReviewsOfRouteWSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllReviewsOfRouteWSCompleted(this, new GetAllReviewsOfRouteWSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateValueWS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateValueWS(Review r, string value, int num) {
            this.Invoke("UpdateValueWS", new object[] {
                        r,
                        value,
                        num});
        }
        
        /// <remarks/>
        public void UpdateValueWSAsync(Review r, string value, int num) {
            this.UpdateValueWSAsync(r, value, num, null);
        }
        
        /// <remarks/>
        public void UpdateValueWSAsync(Review r, string value, int num, object userState) {
            if ((this.UpdateValueWSOperationCompleted == null)) {
                this.UpdateValueWSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateValueWSOperationCompleted);
            }
            this.InvokeAsync("UpdateValueWS", new object[] {
                        r,
                        value,
                        num}, this.UpdateValueWSOperationCompleted, userState);
        }
        
        private void OnUpdateValueWSOperationCompleted(object arg) {
            if ((this.UpdateValueWSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateValueWSCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteReviewWS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteReviewWS(Review r) {
            this.Invoke("DeleteReviewWS", new object[] {
                        r});
        }
        
        /// <remarks/>
        public void DeleteReviewWSAsync(Review r) {
            this.DeleteReviewWSAsync(r, null);
        }
        
        /// <remarks/>
        public void DeleteReviewWSAsync(Review r, object userState) {
            if ((this.DeleteReviewWSOperationCompleted == null)) {
                this.DeleteReviewWSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteReviewWSOperationCompleted);
            }
            this.InvokeAsync("DeleteReviewWS", new object[] {
                        r}, this.DeleteReviewWSOperationCompleted, userState);
        }
        
        private void OnDeleteReviewWSOperationCompleted(object arg) {
            if ((this.DeleteReviewWSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteReviewWSCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Review {
        
        private int idField;
        
        private string contentField;
        
        private int ratingField;
        
        private string captionField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        public int Rating {
            get {
                return this.ratingField;
            }
            set {
                this.ratingField = value;
            }
        }
        
        /// <remarks/>
        public string Caption {
            get {
                return this.captionField;
            }
            set {
                this.captionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AddReviewWSCompletedEventHandler(object sender, AddReviewWSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddReviewWSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddReviewWSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetReviewWSCompletedEventHandler(object sender, GetReviewWSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReviewWSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReviewWSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Review Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Review)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetAllReviewsOfRouteWSCompletedEventHandler(object sender, GetAllReviewsOfRouteWSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllReviewsOfRouteWSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllReviewsOfRouteWSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Review[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Review[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void UpdateValueWSCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void DeleteReviewWSCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591